# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Example Config
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name: myyy gpt-5
    provider: openai
    model: gpt-5
    apiKey: YOUR_OPENAI_API_KEY_HERE
  #- uses: ollama/qwen2.5-coder-7b
  #  with:
  #    apiBase: http://172.30.36.30:11434
  - uses: anthropic/claude-4-sonnet
    with:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

  - name: Ollama Local 7b
    provider: ollama
    model: qwen2.5-coder:7b
    apiBase: http://172.30.36.30:11434
    requestOptions:
      timeout: 60000
      num_ctx: 32768
      
    
  - name: Ollama Local 14b
    provider: ollama
    model: qwen2.5-coder:14b
    apiBase: http://172.30.36.30:11434
    requestOptions:
      timeout: 60000
      num_ctx: 32768

# MCP Servers that Continue can access
# https://docs.continue.dev/customization/mcp-tools
mcpServers:
  - uses: anthropic/memory-mcp
  #- name: "filesystem"
  #  command: "npx"
  #  args: 
  #      - "-y"
  #      - "@modelcontextprotocol/server-filesystem"
  #      - "D:/github/mynote"
